fixups and rebuild

diff --git a/BUILD/pagekite-0.3.19/pagekite.init b/BUILD/pagekite-0.3.19/pagekite.init
--- a/BUILD/pagekite-0.3.19/pagekite.init
+++ b/BUILD/pagekite-0.3.19/pagekite.init
@@ -69,24 +69,24 @@ case "$1" in
 	RETVAL=$?
 	;;
   reload)  {
-	RETVAL=1
-	pagekite=`cat $PAGEKITE_PID 2>/dev/null`
-	echo -n "Reloading pagekite..."
-	if [ -n "${pagekite}" ] && [ -e /proc/"${pagekite}" ]; then
-		kill -HUP $pagekite;
-        	RETVAL=$?
-    	fi
-    	if [ $RETVAL -ne 0 ]; then
-        	failure
-    	else
-        	success
-    	fi
-    	echo
-    	#return $RETVAL
-	}
+#	RETVAL=1
+#	pagekite=`cat $PAGEKITE_PID 2>/dev/null`
+#	echo -n "Reloading pagekite..."
+#	if [ -n "${pagekite}" ] && [ -e /proc/"${pagekite}" ]; then
+#		kill -HUP $pagekite;
+#        	RETVAL=$?
+#    	fi
+#    	if [ $RETVAL -ne 0 ]; then
+#        	failure
+#    	else
+#        	success
+#    	fi
+#    	echo
+#    	#return $RETVAL
+#	}
 	;;
   *)
-	echo "Usage: $0 {start|stop|reload|restart|status|condrestart}"
+	echo "Usage: $0 {start|stop|restart|status|condrestart}"
 	RETVAL=1
 	;;
 esac
